<?php

namespace App\Http\Controllers\Developer;

use App\Helpers\ActivityLogger;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class DatabaseBackupController extends Controller
{
    public function index()
    {
        $database = DB::getDatabaseName();
        $tableCount = count(DB::select('SHOW TABLES'));
        $filenamePattern = Str::slug($database) . '_backup_' . now()->format('Y-m-d_His') . '.sql';

        $user = auth()->user();
        $activeRoute = 'developer.database-backup.index';

        return view('developer.database-backup.index', compact('database', 'tableCount', 'filenamePattern', 'user', 'activeRoute'));
    }

    /**
     * Stream a full SQL export of the database. Route is admin-only.
     */
    public function download()
    {
        $database = DB::getDatabaseName();
        $filename = Str::slug($database) . '_backup_' . now()->format('Y-m-d_His') . '.sql';

        ActivityLogger::log('backup', 'Database', "Downloaded a full SQL backup of the \"{$database}\" database.");

        return response()->streamDownload(function () use ($database) {
            echo "-- Database backup: {$database}\n";
            echo "-- Generated: " . now()->toDateTimeString() . "\n";
            echo "-- Generated by: " . (auth()->user()->email ?? 'system') . "\n\n";
            echo "SET FOREIGN_KEY_CHECKS=0;\n\n";

            foreach (DB::select('SHOW TABLES') as $tableRow) {
                $table = array_values((array) $tableRow)[0];

                $create = DB::select("SHOW CREATE TABLE `{$table}`")[0];
                $createSql = $create->{'Create Table'} ?? $create->{'Create View'} ?? '';

                echo "DROP TABLE IF EXISTS `{$table}`;\n{$createSql};\n\n";

                foreach (DB::table($table)->cursor() as $row) {
                    $data = (array) $row;
                    if (empty($data)) {
                        continue;
                    }

                    $columns = '`' . implode('`, `', array_keys($data)) . '`';
                    $values = implode(', ', array_map(
                        fn ($value) => is_null($value) ? 'NULL' : DB::getPdo()->quote((string) $value),
                        $data
                    ));

                    echo "INSERT INTO `{$table}` ({$columns}) VALUES ({$values});\n";
                }

                echo "\n";
            }

            echo "SET FOREIGN_KEY_CHECKS=1;\n";
        }, $filename, [
            'Content-Type' => 'application/sql',
        ]);
    }
}
